---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:


# https://github.com/GoogleContainerTools/container-diff
    - name: "deploy container-diff analyze (single image) wo snaps on bionic amd64"
      dist: bionic
      arch: amd64
      services:
      - docker 
      language: python
      sudo: false
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
        - docker pull python:3.4-alpine
        - docker images -a | grep "3.4-alpine" | awk '{print $3}'
        - docker image ls
        # By default, with no --type flag specified, container-diff will run image size analysis
        - container-diff analyze python:3.4-alpine
        - container-diff analyze python:3.4-alpine --type=history
        # 2020/11/22 13:15:34 Unable to read "/home/travis/.docker/config.json": open /home/travis/.docker/config.json: no such file or directory
        - sudo container-diff analyze python:3.4-alpine --type=file
        - container-diff analyze python:3.4-alpine --type=size
        # - container-diff analyze python:3.4-alpine --type=rpm #ERRO[0001] Could not detect RPM binary in unpacked image python:3.4-alpine
        - container-diff analyze python:3.4-alpine --type=pip
        - container-diff analyze python:3.4-alpine --type=apt
        - container-diff analyze python:3.4-alpine --type=node 
        - container-diff analyze python:3.4-alpine --type=apt --type=node 
        - container-diff analyze python:3.4-alpine --type=history --type=pip --type=node        
      after_success:
        - deactivate

# https://github.com/GoogleContainerTools/container-diff
    - name: "deploy container-diff diff wo snaps on bionic amd64"
      dist: bionic
      arch: amd64
      services:
      - docker 
      language: python
      sudo: false
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
        - docker pull python:3.4-alpine
        - docker images -a | grep "3.4-alpine" | awk '{print $3}'
        - docker image ls
        # By default, with no --type flag specified, container-diff will run image size analysis
        - container-diff diff alpine:latest debian:bullseye-slim
        - container-diff diff alpine:latest debian:bullseye-slim --type=history
        - container-diff diff alpine:latest debian:bullseye-slim --type=file
        - container-diff diff alpine:latest debian:bullseye-slim --type=size
        - container-diff diff alpine:latest debian:bullseye-slim --type=rpm
        - container-diff diff alpine:latest debian:bullseye-slim --type=pip
        - container-diff diff alpine:latest debian:bullseye-slim --type=apt
        - container-diff diff alpine:latest debian:bullseye-slim --type=node 
        - container-diff diff alpine:latest debian:bullseye-slim --type=apt --type=node 
        - container-diff diff alpine:latest debian:bullseye-slim --type=history --type=pip --type=node        
      after_success:
        - deactivate        